### ISSUE TITLE
GetBoneParent sig outdated

### ISSUE THREAD

**Issue by pogrammerx** [nezu-cc/BakaWare4#5]
Hello, 

I just wanted to mention that your GetBoneParent sig is out of date, I would update it myself and create a pull, but I don't have the new one, or any x-refs.
Update would be appreciated!

Cheers

**Comment by dumbasPL** [comment]
please read https://github.com/nezu-cc/BakaWare4/issues/3

TLDR: future updates are private for now and the foreseeable future, and there is **WAY MORE** broken than just sigs in the ancient version. And no, I'm not selling the cheat.
